name: ambilytics
description: Google Analytics for all Flutter platfroms (Android, iOS, macOS, Web, Windows and Linux)
version: 1.0.7
repository: https://github.com/maxim-saplin/ambilytics
homepage: https://github.com/maxim-saplin/ambilytics

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter:

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  firebase_analytics: ^11.3.1
  firebase_core: ^3.4.1
  shared_preferences: ^2.2.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

false_secrets:
  - example/*